name: "MSMQ App build and release workflow"

on:
  push:
    tags:
      #- '*'
      - "subprocess/v*"

env:
  PROJECT_PATH: MSMQ_Subscriber_Process\MSMQ_Subscriber_Process.csproj

jobs:
  Deploy:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{env.PROJECT_PATH}}

      - name: Build project 
        run: dotnet build ${{env.PROJECT_PATH}} -c Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      - name: Publish package
        run: dotnet publish ${{env.PROJECT_PATH}} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --no-build

      - name: Create release
        uses: actions/create-release@v1
        id: create_release

        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: "Release ${{ github.ref }}"

      - name: Publish artifact(.exe, zip, .tar.gz)
        uses: csexton/release-asset-action@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          pattern: bin/Release/net6.0-windows/win-x64/publish/*.exe
          release-url: ${{steps.create_release.outputs.upload_url}}
